version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    working_directory: ~/heavy-yogurt
    steps:
      - checkout
      - run:
          name: Debug location
          command: pwd
      - run:
          name: Restore packages for all projects in solution
          command: dotnet restore FinalApp   
      - run:
          name: Build all projects in solution
          command: dotnet build FinalApp
      - run:
          name: Run tests in test project
          command: dotnet test FinalAppTest/FinalAppTest.csproj